credentials/urls.py
from . import views
from django.urls import path

app_name = 'credentials_app'

urlpatterns = [
    path("register/", views.register, name='register'),
    path("login/", views.login, name='login'),
    path("logout/", views.logout, name='logout')
]

registerapp/urls.py
from . import views
from django.urls import path

app_name = 'registerapp'

urlpatterns = [
    path('', views.demo, name="demo")
]

user_login/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from user_login import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/traveller/')),
    path('traveller/', include('registerapp.urls')),
    path('credentials/', include('credentials.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credentials/models.py
from django.db import models

# Create your models here.

registerapp/models.py
from django.db import models


# Create your models here.
class guides(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='pics')
    designation = models.TextField()

    def __str__(self):
        return self.name


class reviews(models.Model):
    client = models.CharField(max_length=250)
    profession = models.CharField(max_length=250)
    comments = models.TextField()
    image = models.ImageField(upload_to='pics')

    def __str__(self):
        return self.client

credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['confirm_password']

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username already taken!")
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, "Email already taken!")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, password=password, first_name=first_name,
                                                last_name=last_name, email=email)
                user.save();
                print('user created')
                return redirect('login')
        else:
            messages.info(request, "Passwords not matching!")
            return redirect('register')
    return render(request, 'register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Invalid credentials')
            return redirect('login')

    return render(request, "login.html")


def logout(request):
    auth.logout(request)
    return redirect('/')

registerapp/views.py
from django.shortcuts import render

from .models import guides, reviews


# Create your views here
def demo(request):
    obj = guides.objects.all()
    obj1 = reviews.objects.all()
    return render(request, 'index.html', {'result': obj, 'review': obj1})

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Traveller Login</title>
    <link rel="stylesheet" href="{% static 'style1.css' %}">
   <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  </head>
  <body>
    <div class="bg-img">
      <div class="content">
        <header>Login</header>
        <form action="#" method="post">
          {% csrf_token %}
          {% for i in messages %}
          <div class="error-message">{{ i }} </div>
          {% endfor %}

          <div class="field">
            <span class="fa fa-user"></span>
            <input type="text" placeholder="username" name="username">
          </div>
          <div class="field space">
            <span class="fa fa-lock"></span>
            <input type="password" class="pass-key" placeholder="Password" name="password">
            <span class="show">SHOW</span>
          </div>
          <div class="pass">
            <a href="#">Forgot Password?</a>
          </div>
          <div class="field">
            <input type="submit" value="LOGIN">
          </div>
        </form>
<!--        <div class="login">Or login with</div>-->
<!--        <div class="links">-->
<!--          <div class="facebook">-->
<!--            <i class="fab fa-facebook-f"><span>Facebook</span></i>-->
<!--          </div>-->
<!--          <div class="instagram">-->
<!--            <i class="fab fa-instagram"><span>Instagram</span></i>-->
<!--          </div>-->
<!--        </div>-->
        <div class="signup">Don't have account?
          <a href="{% url 'credentials_app:register' %}">Signup Now</a>
<!--          <button class="field"><a href="{% url 'registerapp:demo' %}" style="text-decoration:none;">Home</a></button>-->
        </div>
      </div>
    </div>

    <script>
      const pass_field = document.querySelector('.pass-key');
      const showBtn = document.querySelector('.show');
      showBtn.addEventListener('click', function(){
       if(pass_field.type === "password"){
         pass_field.type = "text";
         showBtn.textContent = "HIDE";
         showBtn.style.color = "#3498db";
       }else{
         pass_field.type = "password";
         showBtn.textContent = "SHOW";
         showBtn.style.color = "#222";
       }
      });
    </script>


  </body>
</html>

templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Traveller Registration</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
   <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  </head>
  <body>
    <div class="bg-img">
      <h2 class="content">
        <header>Register</header>

        <form action="register" method="post">
          {% csrf_token %}
          {% for i in messages %}
        <div style="color: red; margin: 13px 0; font-family: 'Poppins', sans-serif; text-align: left; font-size: 13px; padding: 10px;">{{i}} </div>
        {% endfor %}
          <div class="field">
            <span class="fa fa-user"></span>
            <input type="text" placeholder="Username" name="username">
          </div>
          <div class="field">
            <span class="fa fa-user"></span>
            <input type="text" placeholder="First name" name="first_name">
          </div>
          <div class="field">
            <span class="fa fa-user"></span>
            <input type="text"  placeholder="Last name" name="last_name">
          </div>
          <div class="field">
            <span class="fa fa-envelope"></span>
            <input type="email" placeholder="Email" name="email">
          </div>
          <div class="field">
            <span class="fa fa-lock"></span>
            <input type="password" class="pass-key" placeholder="Password" name="password">
          </div>
          <div class="field space">
            <span class="fa fa-lock"></span>
            <input type="password" class="pass-key" placeholder="Confirm Password" name="confirm_password">
            <span class="show">SHOW</span>
          </div>

          <div class="field">
            <input type="submit" value="REGISTER">
          </div>
        </form>
        <div class="login">Already have an account? <a href="{% url 'credentials_app:login' %}">Login</a></div>
        <div class="signup">By registering, you agree to our <a href="#">Terms</a> and <a href="#">Privacy Policy</a>.</div>
      </div>
    </div>

    <script>
      const pass_field = document.querySelector('.pass-key');
      const showBtn = document.querySelector('.show');
      showBtn.addEventListener('click', function(){
       if(pass_field.type === "password"){
         pass_field.type = "text";
         showBtn.textContent = "HIDE";
         showBtn.style.color = "#3498db";
       }else{
         pass_field.type = "password";
         showBtn.textContent = "SHOW";
         showBtn.style.color = "#222";
       }
      });
    </script>
  </body>
</html>